-- script to create the database for the sensor data

CREATE TABLE LightSample
(
SampleID INTEGER AUTO_INCREMENT PRIMARY KEY,
SensorID INTEGER,
Value DOUBLE,
Date DATETIME
);

CREATE TABLE TemperatureSample
(
SampleID INTEGER AUTO_INCREMENT PRIMARY KEY,
SensorID INTEGER,
Value DOUBLE,
Date DATETIME
);

CREATE TABLE PressureSample
(
SampleID INTEGER AUTO_INCREMENT PRIMARY KEY,
SensorID INTEGER,
Value DOUBLE,
Date DATETIME
);

CREATE TABLE HumiditySample
(
SampleID INTEGER AUTO_INCREMENT PRIMARY KEY,
SensorID INTEGER,
Value DOUBLE,
Date DATETIME
);

CREATE TABLE SoundSample
(
SampleID INTEGER AUTO_INCREMENT PRIMARY KEY,
SensorID INTEGER,
Value DOUBLE,
Date DATETIME
);